# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 952)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.imageList = QtWidgets.QListWidget(self.splitter)
        self.imageList.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageList.sizePolicy().hasHeightForWidth())
        self.imageList.setSizePolicy(sizePolicy)
        self.imageList.setObjectName("imageList")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.errorLabel = QtWidgets.QLabel(self.frame)
        self.errorLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout_2.addWidget(self.errorLabel)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.infoTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame1 = QtWidgets.QFrame(self.infoTab)
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.formLayout = QtWidgets.QFormLayout(self.frame1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pathEdit = QtWidgets.QLineEdit(self.frame1)
        self.pathEdit.setReadOnly(True)
        self.pathEdit.setObjectName("pathEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pathEdit)
        self.label_2 = QtWidgets.QLabel(self.frame1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.shaEdit = QtWidgets.QLineEdit(self.frame1)
        self.shaEdit.setReadOnly(True)
        self.shaEdit.setObjectName("shaEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.shaEdit)
        self.frame_2 = QtWidgets.QFrame(self.frame1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.crc32Edit = QtWidgets.QLineEdit(self.frame_2)
        self.crc32Edit.setReadOnly(True)
        self.crc32Edit.setObjectName("crc32Edit")
        self.horizontalLayout_5.addWidget(self.crc32Edit)
        self.calcCrc32Edit = QtWidgets.QLineEdit(self.frame_2)
        self.calcCrc32Edit.setReadOnly(True)
        self.calcCrc32Edit.setObjectName("calcCrc32Edit")
        self.horizontalLayout_5.addWidget(self.calcCrc32Edit)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_2)
        self.label_4 = QtWidgets.QLabel(self.frame1)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sha512Edit = QtWidgets.QLineEdit(self.frame1)
        self.sha512Edit.setReadOnly(True)
        self.sha512Edit.setObjectName("sha512Edit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sha512Edit)
        self.label_5 = QtWidgets.QLabel(self.frame1)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.signDigestEdit = QtWidgets.QLineEdit(self.frame1)
        self.signDigestEdit.setReadOnly(True)
        self.signDigestEdit.setObjectName("signDigestEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.signDigestEdit)
        self.label_6 = QtWidgets.QLabel(self.frame1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.frame_3 = QtWidgets.QFrame(self.frame1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.crc32DataEdit = QtWidgets.QLineEdit(self.frame_3)
        self.crc32DataEdit.setReadOnly(True)
        self.crc32DataEdit.setObjectName("crc32DataEdit")
        self.horizontalLayout_6.addWidget(self.crc32DataEdit)
        self.calcCrc32DataEdit = QtWidgets.QLineEdit(self.frame_3)
        self.calcCrc32DataEdit.setReadOnly(True)
        self.calcCrc32DataEdit.setObjectName("calcCrc32DataEdit")
        self.horizontalLayout_6.addWidget(self.calcCrc32DataEdit)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_3)
        self.label_7 = QtWidgets.QLabel(self.frame1)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.frame_4 = QtWidgets.QFrame(self.frame1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.hmacEdit = QtWidgets.QLineEdit(self.frame_4)
        self.hmacEdit.setReadOnly(True)
        self.hmacEdit.setObjectName("hmacEdit")
        self.horizontalLayout_7.addWidget(self.hmacEdit)
        self.calcHmacEdit = QtWidgets.QLineEdit(self.frame_4)
        self.calcHmacEdit.setReadOnly(True)
        self.calcHmacEdit.setObjectName("calcHmacEdit")
        self.horizontalLayout_7.addWidget(self.calcHmacEdit)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frame_4)
        self.label_71 = QtWidgets.QLabel(self.frame1)
        self.label_71.setObjectName("label_71")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_71)
        self.frame_41 = QtWidgets.QFrame(self.frame1)
        self.frame_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_41.setLineWidth(0)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_71.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_71.setSpacing(0)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.hmacDataEdit = QtWidgets.QLineEdit(self.frame_41)
        self.hmacDataEdit.setReadOnly(True)
        self.hmacDataEdit.setObjectName("hmacDataEdit")
        self.horizontalLayout_71.addWidget(self.hmacDataEdit)
        self.calcHmacDataEdit = QtWidgets.QLineEdit(self.frame_41)
        self.calcHmacDataEdit.setReadOnly(True)
        self.calcHmacDataEdit.setObjectName("calcHmacDataEdit")
        self.horizontalLayout_71.addWidget(self.calcHmacDataEdit)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.frame_41)
        self.verticalLayout.addWidget(self.frame1)
        self.groupBox = QtWidgets.QGroupBox(self.infoTab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.signerEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.signerEdit.setReadOnly(True)
        self.signerEdit.setObjectName("signerEdit")
        self.horizontalLayout_4.addWidget(self.signerEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.infoTab, "")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.configTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.configTable = QtWidgets.QTreeWidget(self.configTab)
        self.configTable.setColumnCount(3)
        self.configTable.setObjectName("configTable")
        self.configTable.headerItem().setText(0, "1")
        self.configTable.headerItem().setText(1, "2")
        self.configTable.headerItem().setText(2, "3")
        self.horizontalLayout_2.addWidget(self.configTable)
        self.tabWidget.addTab(self.configTab, "")
        self.filesTab = QtWidgets.QWidget()
        self.filesTab.setObjectName("filesTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.filesTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filesTree = QtWidgets.QTreeWidget(self.filesTab)
        self.filesTree.setColumnCount(2)
        self.filesTree.setObjectName("filesTree")
        self.filesTree.headerItem().setText(0, "1")
        self.filesTree.headerItem().setText(1, "2")
        self.horizontalLayout_3.addWidget(self.filesTree)
        self.tabWidget.addTab(self.filesTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPatch = QtWidgets.QAction(MainWindow)
        self.actionPatch.setObjectName("actionPatch")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionPatch)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.imageList.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(MainWindow.change_image)
        self.filesTree.clicked['QModelIndex'].connect(MainWindow.file_clicked)
        self.actionOpen.triggered.connect(MainWindow.do_open)
        self.actionPatch.triggered.connect(MainWindow.do_patch)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blue Coat File System Manager"))
        self.errorLabel.setText(_translate("MainWindow", "Image is readonly"))
        self.label.setText(_translate("MainWindow", "Path"))
        self.label_2.setText(_translate("MainWindow", "CRC32-Header"))
        self.label_3.setText(_translate("MainWindow", "SHA256-Data"))
        self.shaEdit.setPlaceholderText(_translate("MainWindow", "Doubleclick to calc..."))
        self.calcCrc32Edit.setPlaceholderText(_translate("MainWindow", "Doubleclick to calc..."))
        self.label_4.setText(_translate("MainWindow", "SHA512-Digest"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.label_6.setText(_translate("MainWindow", "CRC32-Data"))
        self.calcCrc32DataEdit.setPlaceholderText(_translate("MainWindow", "Doubleclick to calc..."))
        self.label_7.setText(_translate("MainWindow", "HMAC-Header"))
        self.calcHmacEdit.setPlaceholderText(_translate("MainWindow", "Doubleclick to calc..."))
        self.label_71.setText(_translate("MainWindow", "HMAC-Data"))
        self.calcHmacDataEdit.setPlaceholderText(_translate("MainWindow", "Doubleclick to calc..."))
        self.groupBox.setTitle(_translate("MainWindow", "Signature"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infoTab), _translate("MainWindow", "Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filesTab), _translate("MainWindow", "Files"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionPatch.setText(_translate("MainWindow", "Patch"))

